Repository serge-web/serge, pull requests merged in 2020-10, with the labels that each got.

#519 Feature/514 handle group changes
  packages/components/src/local/map-bar/helpers/asset-dialog-for.spec.ts
  packages/components/src/local/map-bar/helpers/asset-dialog-for.ts
  packages/components/src/local/map-bar/index.tsx
  packages/components/src/local/mapping/helpers/group-create-new-group.spec.ts
  packages/components/src/local/mapping/helpers/group-create-new-group.ts
  packages/components/src/local/mapping/helpers/group-host-platform.spec.ts
  packages/components/src/local/mapping/helpers/group-host-platform.ts
  packages/components/src/local/mapping/helpers/group-move-to-root.spec.ts
  packages/components/src/local/mapping/helpers/group-move-to-root.ts
  packages/components/src/local/mapping/helpers/store-planned-route.spec.ts
  packages/components/src/local/mapping/helpers/store-planned-route.ts
  packages/components/src/local/mapping/index.tsx
  packages/components/src/local/molecules/admin-message/index.stories.tsx
  packages/components/src/local/world-state/index.tsx
  packages/components/src/local/world-state/types/props.d.ts
  packages/custom-types/mapping-context.d.ts
  packages/helpers/find-perceived-as-types.ts
  packages/helpers/is-perceived-by.ts
  packages/helpers/route-create-store.ts
  packages/helpers/tests/find-perceived-as-types.spec.ts
  packages/mocks/forces.mock.ts
Labels: enhancement

#530 Bugfix/529 clear from route
  packages/helpers/route-create-route.ts
  packages/helpers/route-create-store.ts
  packages/helpers/tests/route-create-store.spec.ts
  packages/themes/_gameSetup.scss
  packages/themes/_progress.scss
Labels: bug

#521 Feature/508 submit plans
  packages/components/src/local/adjudicate-turn-form/__snapshots__/index.spec.tsx.snap
  packages/components/src/local/adjudicate-turn-form/index.spec.tsx
  packages/components/src/local/adjudicate-turn-form/index.stories.tsx
  packages/components/src/local/adjudicate-turn-form/index.tsx
  packages/components/src/local/adjudicate-turn-form/types/props.d.ts
  packages/components/src/local/map-bar/index.tsx
  packages/components/src/local/mapping/index.stories.tsx
  packages/components/src/local/mapping/index.tsx
  packages/components/src/local/plan-turn-form/index.spec.tsx
  packages/components/src/local/plan-turn-form/index.stories.tsx
  packages/components/src/local/plan-turn-form/index.tsx
  packages/components/src/local/plan-turn-form/types/props.d.ts
  packages/components/src/local/world-state/index.spec.tsx
  packages/components/src/local/world-state/index.stories.tsx
  packages/components/src/local/world-state/index.tsx
  packages/components/src/local/world-state/types/props.d.ts
  packages/custom-types/mapping-context.d.ts
  packages/server/db/wargame-kdvq9n31
  packages/server/db/wargame-kdvqaiaq
  packages/server/db/wargame-kdvqbbnw
Labels: enhancement

#537 Only allow top level elements to be selected
  packages/components/src/local/world-state/index.tsx
Labels: bug, hacktoberfest-accepted

#548 Update README.md
  packages/components/README.md
Labels: bug
